# Generated by Django 5.1.7 on 2025-04-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_rating_product_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='clothesType',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
